# Generated by Django 5.2.8 on 2025-12-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='career',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
