# Generated by Django 5.2.8 on 2025-11-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_corner', '0002_alter_event_options_alter_materi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='file',
        ),
        migrations.AddField(
            model_name='materi',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
