# Generated by Django 5.2.8 on 2025-12-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('alumni', 'Alumni')], default='mahasiswa', max_length=20),
        ),
    ]
