# Generated by Django 5.2.8 on 2025-12-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorschedule',
            name='hari',
        ),
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='hari',
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorschedule',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_requests', to='users.user'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests', to='users.user'),
        ),
    ]
